"""apply_server_defaults_and_rbac

Revision ID: 6d81bb6854d7
Revises: 760a98db7d90
Create Date: 2026-08-31 16:01:00.050805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d81bb6854d7'
down_revision: Union[str, None] = '760a98db7d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'stock', server_default=sa.text('0'))
    op.alter_column('products', 'featured', server_default=sa.text('false'))
    op.alter_column('products', 'is_active', server_default=sa.text('true'))
    op.alter_column('users', 'is_active', server_default=sa.text('true'))
    op.alter_column('categories', 'is_active', server_default=sa.text('true'))
    op.alter_column('orders', 'status', server_default=sa.text("'pending'"))
    op.alter_column('orders', 'payment_status', server_default=sa.text("'pending'"))
    op.alter_column('orders', 'discount_amount', server_default=sa.text('0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'discount_amount', server_default=None)
    op.alter_column('orders', 'payment_status', server_default=None)
    op.alter_column('orders', 'status', server_default=None)
    op.alter_column('categories', 'is_active', server_default=None)
    op.alter_column('users', 'is_active', server_default=None)
    op.alter_column('products', 'is_active', server_default=None)
    op.alter_column('products', 'featured', server_default=None)
    op.alter_column('products', 'stock', server_default=None)
    # ### end Alembic commands ###
