"""remove_voting

Revision ID: 7c8e73457d01
Revises: 83907244190b
Create Date: 2026-09-01 13:05:03.855177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c8e73457d01'
down_revision: Union[str, None] = '83907244190b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:    # Drop child tables first to avoid dependency errors
    op.drop_index('ix_voting_responses_id', table_name='voting_responses')
    op.drop_index('ix_voting_responses_option_id', table_name='voting_responses')
    op.drop_index('ix_voting_responses_question_id', table_name='voting_responses')
    op.drop_table('voting_responses')

    op.drop_index('ix_voting_options_id', table_name='voting_options')
    op.drop_index('ix_voting_options_question_id', table_name='voting_options')
    op.drop_table('voting_options')

    op.drop_index('ix_voting_questions_id', table_name='voting_questions')
    op.drop_table('voting_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voting_options',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('voting_options_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['voting_questions.id'], name='voting_options_question_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='voting_options_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_voting_options_question_id', 'voting_options', ['question_id'], unique=False)
    op.create_index('ix_voting_options_id', 'voting_options', ['id'], unique=False)
    op.create_table('voting_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['voting_options.id'], name='voting_responses_option_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['voting_questions.id'], name='voting_responses_question_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='voting_responses_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='voting_responses_pkey'),
    sa.UniqueConstraint('question_id', 'option_id', 'user_id', name='uq_vote_user_option')
    )
    op.create_index('ix_voting_responses_question_id', 'voting_responses', ['question_id'], unique=False)
    op.create_index('ix_voting_responses_option_id', 'voting_responses', ['option_id'], unique=False)
    op.create_index('ix_voting_responses_id', 'voting_responses', ['id'], unique=False)
    op.create_table('voting_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('allow_multiple_answers', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('allow_anonymous', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='voting_questions_created_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='voting_questions_pkey')
    )
    op.create_index('ix_voting_questions_id', 'voting_questions', ['id'], unique=False)
    # ### end Alembic commands ###
